### ISSUE TITLE
Getting a selected Todo

### ISSUE THREAD

**Issue by scottfoltz** [tarlepp/angular-firebase-material-demo#1]
More of a question, than an issue. 

I have been playing around with this code and wanted to add a TaskDetail Component. When a list item is clicked I want the Component to display all the data for that specific task.  

Will I need to create a separate 'TodoResolver' to grab a single items data to go along with the existing 'TodosResolver' that grabs the entire list?

Since in TodosComponent you do this...
`  public ngOnInit() {
         this.activatedRoute.data.subscribe(data => {
      this.todos = data['todos'];
    });
  }
`
Do I have the ability to grab the selectedTodo data from 'this.todos'?

**Comment by tarlepp** [comment]
Actually those resolves aren't so good with firebase resolves. So basically I would pass that todo item id to your detail component and inside that component I would just fetch that resource item from firebase.,

And if you want to use already fetched items just do something like `<button (click)="showDetails(todoItem)">show details</button>` so in here you have the "selected" item that you use.

**Comment by scottfoltz** [comment]
In this case, I would be using an @Input selector for my TodoDetailComponent, right?
`export class TodoDetailComponent extends Animations implements OnInit  {
`
`@Input() item: TodoItem;
`

TodoDetailComponent.html
`<h5>{{item.todo}}</h5>`

In my TodosComponent.html I add the TodoDetailComponent 
`
<todo-detail [item] = "selectedItem"></todo-detail>
`

Does the listItem need a click() event handler that grabs the item text to then set to the SelectedItem?

`    <md-list-item
      *ngFor="let item of todos | async"
      [class.active]="item.active"`
`      [class.done]="item.done"
      `
` (mouseenter)="item.active = false" `
`(mouseleave)="item.active = true"`
`(click)="showDetails(todoItem)">`

I am missing something, but I'm not sure what else I need to do.

Thank you for the help in advance!
